export const token =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdG5hbWUiOiJKZWZmIiwibGFzdG5hbWUiOiJCZXpvcyIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInVzZXJfcGFzcyI6ImplZmYxMjMifSwiaWF0IjoxNjI2ODc2OTUzfQ._ivTwdx36bEDUAWgbAYejC7YpjTeQUAABy9wZszvewE";
